<?php
/**
 * GatewayPolicy
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Gateway API
 *
 * Merchant Gateway API
 *
 * OpenAPI spec version: 1.2.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * GatewayPolicy Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GatewayPolicy {
    const SYSTEM_DEFAULT = 'SYSTEM_DEFAULT';
    const PAYFAC_STANDARD = 'PAYFAC_STANDARD';
    const NON_PAYFAC_STANDARD = 'NON_PAYFAC_STANDARD';
    const RESTRICT_PAYPAL = 'RESTRICT_PAYPAL';
    const VOID_ONLY = 'VOID_ONLY';
    

    
}

