<?php
/**
 * Gateway
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Gateway API
 *
 * Merchant Gateway API
 *
 * OpenAPI spec version: 1.2.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Gateway Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Gateway {
    const WORLDPAY = 'WORLDPAY';
    const PAYPAL_US = 'PAYPAL_US';
    const PAYPAL_UK = 'PAYPAL_UK';
    const PAYPAL_IE = 'PAYPAL_IE';
    const PAYVISION = 'PAYVISION';
    const STRIPE = 'STRIPE';
    const SOFORT = 'SOFORT';
    const PAGBRASIL = 'PAGBRASIL';
    const PAPAYA = 'PAPAYA';
    

    
}

