<?php
/**
 * Method
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Gateway API
 *
 * Merchant Gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Method Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Method {
    const GENERIC = 'GENERIC';
    const VISA = 'VISA';
    const VISA_DEBIT = 'VISA_DEBIT';
    const VISA_ELECTRON = 'VISA_ELECTRON';
    const MASTERCARD = 'MASTERCARD';
    const MASTERCARD_DEBIT = 'MASTERCARD_DEBIT';
    const MAESTRO = 'MAESTRO';
    const AMEX = 'AMEX';
    const DINERSCLUB = 'DINERSCLUB';
    const DISCOVER = 'DISCOVER';
    const JCB = 'JCB';
    const CARTE_BANCAIRE = 'CARTE_BANCAIRE';
    const CARTE_BLUE = 'CARTE_BLUE';
    const LASER = 'LASER';
    const DANKORT = 'DANKORT';
    const IDEAL = 'IDEAL';
    const YANDEX = 'YANDEX';
    const QIWI = 'QIWI';
    const ALIPAY = 'ALIPAY';
    const UNIONPAY = 'UNIONPAY';
    const HIPERCARD = 'HIPERCARD';
    const ELO = 'ELO';
    const AURA = 'AURA';
    const BOLETO = 'BOLETO';
    const SEPA = 'SEPA';
    const PAYPAL_EXPRESS = 'PAYPAL_EXPRESS';
    const SOFORT = 'SOFORT';
    const VOID = 'VOID';
    

    
}

