<?php
/**
 * MerchantGatewayVersionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Gateway API
 *
 * Merchant Gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MerchantGatewayVersionTest Class Doc Comment
 *
 * @category    Class */
// * @description MerchantGatewayVersion
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MerchantGatewayVersionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MerchantGatewayVersion"
     */
    public function testMerchantGatewayVersion()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {

    }

    /**
     * Test attribute "gateways"
     */
    public function testPropertyGateways()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

}
