<?php
/**
 * MerchantGatewaysConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Merchant Gateway API
 *
 * Merchant Gateway API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * MerchantGatewaysConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MerchantGatewaysConfigurationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for activateMerchantGatewayVersion
     *
     * activate gateway version.
     *
     */
    public function testActivateMerchantGatewayVersion()
    {

    }

    /**
     * Test case for createMerchantGateway
     *
     * create merchant gateway configuration.
     *
     */
    public function testCreateMerchantGateway()
    {

    }

    /**
     * Test case for createMerchantGatewayVersion
     *
     * create a new gateway configuration version..
     *
     */
    public function testCreateMerchantGatewayVersion()
    {

    }

    /**
     * Test case for getMerchantGateway
     *
     * get merchant gateway configuration.
     *
     */
    public function testGetMerchantGateway()
    {

    }

    /**
     * Test case for getMerchantGatewayVersion
     *
     * get gateway version detail.
     *
     */
    public function testGetMerchantGatewayVersion()
    {

    }

    /**
     * Test case for updateMerchantGatewayVersion
     *
     * update gateway version detail.
     *
     */
    public function testUpdateMerchantGatewayVersion()
    {

    }

}
